services:
  db:
    image: postgres:18
    env_file:
      - ./.envs/.production/.env
    environment:
      - DB_HOST=db
    ports:
      - "5432:5432"
    volumes:
      - prod_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", 'sh -c ''pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" || exit 1''']
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    depends_on:
      db:
        condition: service_healthy

    build:
      context: .
      dockerfile: Dockerfile
      target: runtime

    env_file:
      - ./.envs/.production/.env
    environment:
      - DB_HOST=db
      - RUN_TESTS=true
      - DJANGO_ENV=production

    entrypoint: ["/app/entrypoint.sh"]

    volumes:
      - .:/app
      - venv_cache:/app/.venv

    command: ["gunicorn", "codex_test.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]

    ports:
      - "8000:8000"

volumes:
  prod_postgres_data:
  venv_cache:
